// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ApproveMomentArtifactsData, ApproveMomentArtifactsErrors, ApproveMomentArtifactsResponses, AskCorpusData, AskCorpusErrors, AskCorpusResponses, AssignMeetingProjectData, AssignMeetingProjectErrors, AssignMeetingProjectResponses, AssignMeetingSeriesData, AssignMeetingSeriesErrors, AssignMeetingSeriesResponses, AssignProjectProductData, AssignProjectProductErrors, AssignProjectProductResponses, CreateIngestData, CreateIngestErrors, CreateIngestResponses, CreateProductData, CreateProductErrors, CreateProductResponses, CreateProjectData, CreateProjectErrors, CreateProjectResponses, CreateSeriesData, CreateSeriesErrors, CreateSeriesResponses, GetConfigurationData, GetConfigurationResponses, GetCorpusStatsData, GetCorpusStatsResponses, GetExtractionPromptsData, GetExtractionPromptsResponses, GetHealthData, GetHealthResponses, GetJobData, GetJobErrors, GetJobResponses, GetMediaFileData, GetMediaFileErrors, GetMediaFileResponses, GetMeetingDrilldownData, GetMeetingDrilldownErrors, GetMeetingDrilldownResponses, GetMomentData, GetMomentErrors, GetMomentResponses, GetRecordingData, GetRecordingErrors, GetRecordingResponses, GetSystemStatusData, GetSystemStatusResponses, ListMeetingMomentsData, ListMeetingMomentsErrors, ListMeetingMomentsResponses, ListMeetingsData, ListMeetingsResponses, ListParticipantsData, ListParticipantsResponses, ListProductsData, ListProductsResponses, ListProjectsData, ListProjectsResponses, ListSeriesData, ListSeriesResponses, MergeParticipantsData, MergeParticipantsErrors, MergeParticipantsResponses, RenameParticipantData, RenameParticipantErrors, RenameParticipantResponses, SearchCorpusData, SearchCorpusErrors, SearchCorpusResponses, StreamJobEventsData, StreamJobEventsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create Ingest
 */
export const createIngest = <ThrowOnError extends boolean = false>(options: Options<CreateIngestData, ThrowOnError>): RequestResult<CreateIngestResponses, CreateIngestErrors, ThrowOnError> => (options.client ?? client).post<CreateIngestResponses, CreateIngestErrors, ThrowOnError>({
    url: '/ingests',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Stream Job Events
 */
export const streamJobEvents = <ThrowOnError extends boolean = false>(options?: Options<StreamJobEventsData, ThrowOnError, unknown>): Promise<ServerSentEventsResult<StreamJobEventsResponses>> => (options?.client ?? client).sse.get<StreamJobEventsResponses, unknown, ThrowOnError>({ url: '/jobs/events', ...options });

/**
 * Get Job
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> => (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({ url: '/jobs/{job_id}', ...options });

/**
 * List Meetings
 */
export const listMeetings = <ThrowOnError extends boolean = false>(options?: Options<ListMeetingsData, ThrowOnError>): RequestResult<ListMeetingsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListMeetingsResponses, unknown, ThrowOnError>({ url: '/meetings', ...options });

/**
 * List Meeting Moments
 */
export const listMeetingMoments = <ThrowOnError extends boolean = false>(options: Options<ListMeetingMomentsData, ThrowOnError>): RequestResult<ListMeetingMomentsResponses, ListMeetingMomentsErrors, ThrowOnError> => (options.client ?? client).get<ListMeetingMomentsResponses, ListMeetingMomentsErrors, ThrowOnError>({ url: '/meetings/{meeting_id}/moments', ...options });

/**
 * Get Moment
 */
export const getMoment = <ThrowOnError extends boolean = false>(options: Options<GetMomentData, ThrowOnError>): RequestResult<GetMomentResponses, GetMomentErrors, ThrowOnError> => (options.client ?? client).get<GetMomentResponses, GetMomentErrors, ThrowOnError>({ url: '/moments/{moment_id}', ...options });

/**
 * Approve Moment Artifacts
 *
 * The per-moment approval gesture (story 4.3, epics AC1/AC2/AC3).
 *
 * One request advances every `extracted` artifact under this moment through
 * both `approved` and `published` — there is no separate human gesture for
 * the middle state (Design Notes). Each row is exported to
 * `MM_PUBLISH_ROOT` and, for `adr` rows, git-committed there *before* the
 * Postgres `UPDATE`: a filesystem or git failure must leave every affected
 * row `extracted`, never half-published (AD-4/AD-5).
 */
export const approveMomentArtifacts = <ThrowOnError extends boolean = false>(options: Options<ApproveMomentArtifactsData, ThrowOnError>): RequestResult<ApproveMomentArtifactsResponses, ApproveMomentArtifactsErrors, ThrowOnError> => (options.client ?? client).post<ApproveMomentArtifactsResponses, ApproveMomentArtifactsErrors, ThrowOnError>({ url: '/moments/{moment_id}/approve', ...options });

/**
 * Get Meeting Drilldown
 *
 * One meeting's whole evidence surface (story 2.3, UX-DR5).
 *
 * The header with the meeting-level `sourceDeepLink`, the screenshot series
 * in `ordinal` order — each capture labeled with its stored classification
 * and carrying the live moment that names it — and the full transcript,
 * each segment naming the moment covering it through `moment_segment`.
 * Uncovered segments and unclaimed screenshots appear with a NULL
 * `momentId`; superseded moments appear in neither mapping.
 */
export const getMeetingDrilldown = <ThrowOnError extends boolean = false>(options: Options<GetMeetingDrilldownData, ThrowOnError>): RequestResult<GetMeetingDrilldownResponses, GetMeetingDrilldownErrors, ThrowOnError> => (options.client ?? client).get<GetMeetingDrilldownResponses, GetMeetingDrilldownErrors, ThrowOnError>({ url: '/meetings/{meeting_id}/drilldown', ...options });

/**
 * Search Corpus
 */
export const searchCorpus = <ThrowOnError extends boolean = false>(options: Options<SearchCorpusData, ThrowOnError>): RequestResult<SearchCorpusResponses, SearchCorpusErrors, ThrowOnError> => (options.client ?? client).get<SearchCorpusResponses, SearchCorpusErrors, ThrowOnError>({ url: '/search', ...options });

/**
 * Ask Corpus
 *
 * Answer one question with citations, or refuse — never anything between.
 *
 * Both representations come from the same validated answer. `Accept:
 * text/event-stream` gets `chat.token` / `chat.citations` / `chat.done`;
 * everything else gets the JSON body. The gate runs before either is chosen,
 * so a rejection is a `422` problem in both cases and the stream never opens.
 */
export const askCorpus = <ThrowOnError extends boolean = false>(options: Options<AskCorpusData, ThrowOnError>): RequestResult<AskCorpusResponses, AskCorpusErrors, ThrowOnError> => (options.client ?? client).post<AskCorpusResponses, AskCorpusErrors, ThrowOnError>({
    url: '/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Recording
 *
 * Stream a meeting's recording from its source drop, read-only.
 *
 * The drop is write-once (AD-1/AD-13) and nothing here copies, moves or
 * rewrites it. The stored path is relative to ``MM_DROPS_ROOT`` and is
 * resolved here; neither the root nor the resolved path ever reaches the
 * client, which only ever names the meeting.
 */
export const getRecording = <ThrowOnError extends boolean = false>(options: Options<GetRecordingData, ThrowOnError>): RequestResult<GetRecordingResponses, GetRecordingErrors, ThrowOnError> => (options.client ?? client).get<GetRecordingResponses, GetRecordingErrors, ThrowOnError>({ url: '/media/recordings/{meeting_id}', ...options });

/**
 * Get Media File
 *
 * Stream one content-root-relative file — a screenshot or a frame (AD-3).
 */
export const getMediaFile = <ThrowOnError extends boolean = false>(options: Options<GetMediaFileData, ThrowOnError>): RequestResult<GetMediaFileResponses, GetMediaFileErrors, ThrowOnError> => (options.client ?? client).get<GetMediaFileResponses, GetMediaFileErrors, ThrowOnError>({ url: '/media/{path}', ...options });

/**
 * Get Configuration
 *
 * The allowlist projection of Settings. Reads no secret; mutates nothing.
 */
export const getConfiguration = <ThrowOnError extends boolean = false>(options?: Options<GetConfigurationData, ThrowOnError>): RequestResult<GetConfigurationResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetConfigurationResponses, unknown, ThrowOnError>({ url: '/config', ...options });

/**
 * Get Extraction Prompts
 */
export const getExtractionPrompts = <ThrowOnError extends boolean = false>(options?: Options<GetExtractionPromptsData, ThrowOnError>): RequestResult<GetExtractionPromptsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetExtractionPromptsResponses, unknown, ThrowOnError>({ url: '/extraction/prompts', ...options });

/**
 * List Participants
 */
export const listParticipants = <ThrowOnError extends boolean = false>(options?: Options<ListParticipantsData, ThrowOnError>): RequestResult<ListParticipantsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListParticipantsResponses, unknown, ThrowOnError>({ url: '/participants', ...options });

/**
 * Rename Participant
 *
 * Edit a canonical participant's display name (AD-5).
 *
 * `identity_key`/`normalized_name` never change here — those are the
 * worker's roster-matching keys, and a rename must not disturb intake
 * matching for future meetings.
 *
 * Deliberately READ COMMITTED, not the REPEATABLE READ the read routes use
 * (`moments.py`): `_fetch_participant`'s `FOR UPDATE OF p` blocks a
 * concurrent rename/merge of this same id until this transaction commits,
 * but the `_is_aliased` check that follows reads a *different* table
 * (`participant_alias`, never locked, since a not-yet-existing row cannot
 * be locked). Under REPEATABLE READ that check would keep using the
 * snapshot taken when this transaction opened even after the lock wait —
 * silently stale. READ COMMITTED gives every statement a fresh snapshot, so
 * the check sees whatever the lock wait just resolved.
 */
export const renameParticipant = <ThrowOnError extends boolean = false>(options: Options<RenameParticipantData, ThrowOnError>): RequestResult<RenameParticipantResponses, RenameParticipantErrors, ThrowOnError> => (options.client ?? client).patch<RenameParticipantResponses, RenameParticipantErrors, ThrowOnError>({
    url: '/participants/{participant_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Merge Participants
 *
 * Absorb one canonical participant into another (AD-5).
 *
 * Writes exactly one row: `participant_alias(alias_key, participant_id)`
 * mapping the absorbed identity key to the survivor's id — the mechanism
 * `align._resolve_participants` already reads first and unconditionally, so
 * the merge survives every future re-ingest and stage rerun. No chained
 * aliases: both sides must be canonical (Design Notes), so a later A->B->C
 * collapse is done by merging A directly onto C once B->C exists.
 */
export const mergeParticipants = <ThrowOnError extends boolean = false>(options: Options<MergeParticipantsData, ThrowOnError>): RequestResult<MergeParticipantsResponses, MergeParticipantsErrors, ThrowOnError> => (options.client ?? client).post<MergeParticipantsResponses, MergeParticipantsErrors, ThrowOnError>({
    url: '/participants/{participant_id}/merge',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Corpus Stats
 */
export const getCorpusStats = <ThrowOnError extends boolean = false>(options?: Options<GetCorpusStatsData, ThrowOnError>): RequestResult<GetCorpusStatsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCorpusStatsResponses, unknown, ThrowOnError>({ url: '/corpus/stats', ...options });

/**
 * Get Status
 *
 * Aggregate current-state health. Read-only; mutates nothing anywhere.
 */
export const getSystemStatus = <ThrowOnError extends boolean = false>(options?: Options<GetSystemStatusData, ThrowOnError>): RequestResult<GetSystemStatusResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetSystemStatusResponses, unknown, ThrowOnError>({ url: '/status', ...options });

/**
 * List Series
 */
export const listSeries = <ThrowOnError extends boolean = false>(options?: Options<ListSeriesData, ThrowOnError>): RequestResult<ListSeriesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSeriesResponses, unknown, ThrowOnError>({ url: '/series', ...options });

/**
 * Create Series
 */
export const createSeries = <ThrowOnError extends boolean = false>(options: Options<CreateSeriesData, ThrowOnError>): RequestResult<CreateSeriesResponses, CreateSeriesErrors, ThrowOnError> => (options.client ?? client).post<CreateSeriesResponses, CreateSeriesErrors, ThrowOnError>({
    url: '/series',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Products
 */
export const listProducts = <ThrowOnError extends boolean = false>(options?: Options<ListProductsData, ThrowOnError>): RequestResult<ListProductsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListProductsResponses, unknown, ThrowOnError>({ url: '/products', ...options });

/**
 * Create Product
 */
export const createProduct = <ThrowOnError extends boolean = false>(options: Options<CreateProductData, ThrowOnError>): RequestResult<CreateProductResponses, CreateProductErrors, ThrowOnError> => (options.client ?? client).post<CreateProductResponses, CreateProductErrors, ThrowOnError>({
    url: '/products',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Projects
 */
export const listProjects = <ThrowOnError extends boolean = false>(options?: Options<ListProjectsData, ThrowOnError>): RequestResult<ListProjectsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListProjectsResponses, unknown, ThrowOnError>({ url: '/projects', ...options });

/**
 * Create Project
 */
export const createProject = <ThrowOnError extends boolean = false>(options: Options<CreateProjectData, ThrowOnError>): RequestResult<CreateProjectResponses, CreateProjectErrors, ThrowOnError> => (options.client ?? client).post<CreateProjectResponses, CreateProjectErrors, ThrowOnError>({
    url: '/projects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Assign Project Product
 *
 * Assign a project to a product, or clear it (`productId: null`).
 *
 * `PRODUCT ||--o{ PROJECT`: the assignment is a single nullable column on
 * the project row, so this is an UPDATE, never a second row.
 */
export const assignProjectProduct = <ThrowOnError extends boolean = false>(options: Options<AssignProjectProductData, ThrowOnError>): RequestResult<AssignProjectProductResponses, AssignProjectProductErrors, ThrowOnError> => (options.client ?? client).patch<AssignProjectProductResponses, AssignProjectProductErrors, ThrowOnError>({
    url: '/projects/{project_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Assign Meeting Series
 *
 * Declare (or clear) which series this meeting belongs to.
 *
 * PUT with a nullable id: membership is a single-valued property of the
 * meeting, so PUT replaces it idempotently and `null` clears it — no second
 * DELETE route per relation. The `meeting_series` PRIMARY KEY makes the
 * replace an upsert of one row.
 */
export const assignMeetingSeries = <ThrowOnError extends boolean = false>(options: Options<AssignMeetingSeriesData, ThrowOnError>): RequestResult<AssignMeetingSeriesResponses, AssignMeetingSeriesErrors, ThrowOnError> => (options.client ?? client).put<AssignMeetingSeriesResponses, AssignMeetingSeriesErrors, ThrowOnError>({
    url: '/meetings/{meeting_id}/series',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Assign Meeting Project
 *
 * Declare (or clear) which project scopes this meeting.
 *
 * Same PUT-with-nullable-id shape as the series assignment above.
 */
export const assignMeetingProject = <ThrowOnError extends boolean = false>(options: Options<AssignMeetingProjectData, ThrowOnError>): RequestResult<AssignMeetingProjectResponses, AssignMeetingProjectErrors, ThrowOnError> => (options.client ?? client).put<AssignMeetingProjectResponses, AssignMeetingProjectErrors, ThrowOnError>({
    url: '/meetings/{meeting_id}/project',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });
