// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AcquisitionAccepted
 */
export type AcquisitionAccepted = {
    /**
     * Acquisitionid
     */
    acquisitionId: string;
    /**
     * Sourceid
     */
    sourceId: string;
    /**
     * Status
     */
    status: string;
    /**
     * Kind
     */
    kind: string;
};

/**
 * AcquisitionRefusal
 */
export type AcquisitionRefusal = {
    /**
     * Rule
     */
    rule: string;
    /**
     * Detail
     */
    detail: string;
    /**
     * Remediation
     */
    remediation: string;
};

/**
 * AcquisitionRequest
 *
 * One source, named exactly one way.
 *
 * ``url`` for a published video, ``uploadSessionId`` for files already handed
 * to ``POST /uploads``. Both, or neither, is a refusal rather than a
 * precedence rule: a client that sent both does not know which one it meant,
 * and guessing would acquire the wrong meeting.
 */
export type AcquisitionRequest = {
    /**
     * Url
     */
    url?: string | null;
    /**
     * Uploadsessionid
     */
    uploadSessionId?: string | null;
};

/**
 * AcquisitionSource
 */
export type AcquisitionSource = {
    /**
     * Sourceid
     */
    sourceId: string;
    /**
     * Tool
     */
    tool?: string | null;
    /**
     * Toolversion
     */
    toolVersion?: string | null;
};

/**
 * AcquisitionStatus
 */
export type AcquisitionStatus = {
    /**
     * Acquisitionid
     */
    acquisitionId: string;
    /**
     * Sourceid
     */
    sourceId: string;
    /**
     * Url
     */
    url: string;
    /**
     * Status
     */
    status: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Uploadsessionid
     */
    uploadSessionId?: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    /**
     * Result
     */
    result?: string | null;
    /**
     * Jobid
     */
    jobId?: string | null;
    /**
     * Meetingid
     */
    meetingId?: string | null;
    source?: AcquisitionSource | null;
    refusal?: AcquisitionRefusal | null;
    /**
     * Logtail
     */
    logTail: Array<string>;
};

/**
 * AlignView
 */
export type AlignView = {
    /**
     * Anchorwindowseconds
     */
    anchorWindowSeconds: number;
    /**
     * Minmatchscore
     */
    minMatchScore: number;
    /**
     * Maxsegmentms
     */
    maxSegmentMs: number;
};

/**
 * ApiKnobsView
 */
export type ApiKnobsView = {
    /**
     * Jobeventspollseconds
     */
    jobEventsPollSeconds: number;
    /**
     * Jobeventsheartbeatseconds
     */
    jobEventsHeartbeatSeconds: number;
    search: SearchKnobsView;
    chat: ChatKnobsView;
};

/**
 * ArtifactCounts
 *
 * Extracted artifacts, total and split two ways.
 *
 * Both splits are dynamic dicts rather than fixed fields so a kind or state
 * the CHECK constraint gains later is counted without an api change — the
 * values come straight from GROUP BY, never from a hardcoded list.
 */
export type ArtifactCounts = {
    /**
     * Total
     */
    total: number;
    /**
     * Bykind
     */
    byKind: {
        [key: string]: number;
    };
    /**
     * Bystate
     */
    byState: {
        [key: string]: number;
    };
};

/**
 * AssignMeetingProjectRequest
 *
 * `projectId` is required but nullable: `null` clears the assignment.
 */
export type AssignMeetingProjectRequest = {
    /**
     * Projectid
     */
    projectId: string | null;
};

/**
 * AssignMeetingSeriesRequest
 *
 * `seriesId` is required but nullable: `null` clears the assignment.
 */
export type AssignMeetingSeriesRequest = {
    /**
     * Seriesid
     */
    seriesId: string | null;
};

/**
 * AssignProjectProductRequest
 *
 * `productId` is required but nullable: `null` clears the assignment.
 */
export type AssignProjectProductRequest = {
    /**
     * Productid
     */
    productId: string | null;
};

/**
 * AssignSpeakerRequest
 *
 * Exactly one of three choices, as the story's first clause names them.
 *
 * Three optional fields rather than a discriminated union, because that is
 * the shape the UI's three gestures produce (pick a suggestion, type a name,
 * press *Unresolved*); the validator makes the "exactly one" rule explicit
 * instead of leaving a two-field request to be resolved by precedence.
 *
 * ``unresolved: false`` selects nothing, on purpose — it is the field's
 * default, so counting it as a choice would make an empty body mean
 * "unresolve", which is a destructive reading of silence.
 */
export type AssignSpeakerRequest = {
    /**
     * Participantid
     */
    participantId?: string | null;
    /**
     * Displayname
     */
    displayName?: string | null;
    /**
     * Unresolved
     */
    unresolved?: boolean;
};

/**
 * BandsTimeline
 */
export type BandsTimeline = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Colorordinal
     */
    colorOrdinal: number;
    /**
     * Windowfrom
     */
    windowFrom?: string | null;
    /**
     * Windowto
     */
    windowTo?: string | null;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Meetingcount
     */
    meetingCount: number;
    /**
     * Momentcount
     */
    momentCount: number;
    /**
     * Level
     */
    level: 'bands';
    /**
     * Bucketms
     */
    bucketMs?: number | null;
    /**
     * Bucketcount
     */
    bucketCount: number;
    /**
     * Bands
     */
    bands: Array<TimelineBand>;
};

/**
 * CatalogEntryView
 *
 * One binding a role may be served by, as a picker renders it.
 */
export type CatalogEntryView = {
    /**
     * Binding
     */
    binding: string;
    /**
     * Label
     */
    label: string;
    /**
     * Provider
     */
    provider: string | null;
};

/**
 * ChatKnobsView
 */
export type ChatKnobsView = {
    /**
     * Retrievallimit
     */
    retrievalLimit: number;
    /**
     * Traversalrowlimit
     */
    traversalRowLimit: number;
};

/**
 * ChatRequest
 *
 * One question. camelCase in, like every other body this api takes.
 */
export type ChatRequest = {
    /**
     * Question
     */
    question: string;
};

/**
 * ChatResponse
 */
export type ChatResponse = {
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
    /**
     * Citations
     */
    citations: Array<CitationModel>;
    route: RouteModel;
};

/**
 * ChunkingView
 */
export type ChunkingView = {
    /**
     * Chunkmaxchars
     */
    chunkMaxChars: number;
    /**
     * Chunkoverlapturns
     */
    chunkOverlapTurns: number;
};

/**
 * CitationModel
 *
 * AD-15's citation, and exactly AD-15's citation.
 *
 * Six fields, no more: the web app and the eval harness both consume this
 * array, and a field added here for one consumer's convenience is a field the
 * other starts depending on. ``screenshotId`` is absent on a transcript-only
 * meeting, where ``sourceDeepLink`` carries UX-DR11's transitional affordance
 * in its place — consumers read the fields rather than assuming replay exists.
 */
export type CitationModel = {
    /**
     * Momentid
     */
    momentId: string;
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Endms
     */
    endMs: number;
    /**
     * Screenshotid
     */
    screenshotId?: string | null;
    /**
     * Sourcedeeplink
     */
    sourceDeepLink?: string | null;
};

/**
 * ComponentStatus
 *
 * One dependency row: what it is, whether it works, what to do (CAP-2).
 */
export type ComponentStatus = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * State
     */
    state: 'ok' | 'degraded';
    /**
     * Detail
     */
    detail: string;
    /**
     * Remediation
     */
    remediation?: string | null;
};

/**
 * ConfigResponse
 *
 * The live stack, as config.yaml binds it. No secret, ever.
 */
export type ConfigResponse = {
    /**
     * Service
     */
    service: string;
    /**
     * Configversion
     */
    configVersion: number;
    /**
     * Llmroles
     */
    llmRoles: Array<LlmRoleView>;
    /**
     * Providers
     */
    providers: {
        [key: string]: string;
    };
    embedder: EmbedderView;
    stt: SttView;
    ocr: OcrView;
    diarizer: DiarizerView;
    pipeline: PipelineView;
    projections: ProjectionsView;
    api: ApiKnobsView;
    stores: StoresView;
};

/**
 * CorpusStats
 *
 * The corpus's scale, as the home screen states it (CAP-1).
 */
export type CorpusStats = {
    /**
     * Meetings
     */
    meetings: number;
    /**
     * Totaldurationms
     */
    totalDurationMs: number;
    /**
     * Moments
     */
    moments: number;
    /**
     * Screens
     */
    screens: number;
    /**
     * Screenshots
     */
    screenshots: number;
    artifacts: ArtifactCounts;
    /**
     * Participants
     */
    participants: number;
    /**
     * Publisheddocuments
     */
    publishedDocuments: number;
};

/**
 * CreateNamedEntityRequest
 */
export type CreateNamedEntityRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * CreateProjectRequest
 */
export type CreateProjectRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Productid
     */
    productId?: string | null;
};

/**
 * DiarizerView
 */
export type DiarizerView = {
    /**
     * Engine
     */
    engine: string;
};

/**
 * DrilldownScreenshot
 *
 * One capture in the meeting's screenshot series, in `ordinal` order.
 *
 * `view_type` is the stored `screenshot.view_type` (slide / ui-screen /
 * participant-gallery) and `screen_label` the human-edited `screen.label`
 * when set. `moment_id` is the live moment carrying this `screenshot_id` —
 * NULL when only a superseded moment (or none at all) names it.
 */
export type DrilldownScreenshot = {
    /**
     * Screenshotid
     */
    screenshotId: string;
    /**
     * Ordinal
     */
    ordinal: number;
    /**
     * Startoffsetms
     */
    startOffsetMs: number;
    /**
     * Endoffsetms
     */
    endOffsetMs: number;
    /**
     * Path
     */
    path: string;
    /**
     * Viewtype
     */
    viewType: 'slide' | 'ui-screen' | 'participant-gallery';
    /**
     * Screenlabel
     */
    screenLabel?: string | null;
    /**
     * Classificationtags
     */
    classificationTags: Array<string>;
    /**
     * Momentid
     */
    momentId?: string | null;
};

/**
 * DrilldownSegment
 *
 * One transcript segment of the whole meeting, in `ordinal` order.
 *
 * The segment fields spell exactly what `MomentSegment` spells; `moment_id`
 * is the live moment covering it through `moment_segment` — NULL for an
 * uncovered segment.
 */
export type DrilldownSegment = {
    /**
     * Segmentid
     */
    segmentId: string;
    /**
     * Ordinal
     */
    ordinal: number;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Endms
     */
    endMs: number;
    /**
     * Speakerlabel
     */
    speakerLabel: string;
    /**
     * Speakerresolution
     */
    speakerResolution?: string | null;
    /**
     * Participantid
     */
    participantId?: string | null;
    /**
     * Text
     */
    text: string;
    /**
     * Momentid
     */
    momentId?: string | null;
};

/**
 * EmbedderView
 */
export type EmbedderView = {
    /**
     * Model
     */
    model: string;
    /**
     * Dimension
     */
    dimension: number;
};

/**
 * EvidenceTimeline
 */
export type EvidenceTimeline = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Colorordinal
     */
    colorOrdinal: number;
    /**
     * Windowfrom
     */
    windowFrom?: string | null;
    /**
     * Windowto
     */
    windowTo?: string | null;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Meetingcount
     */
    meetingCount: number;
    /**
     * Momentcount
     */
    momentCount: number;
    /**
     * Level
     */
    level: 'evidence';
    /**
     * Truncated
     */
    truncated: boolean;
    /**
     * Evidence
     */
    evidence: Array<TimelineEvidence>;
};

/**
 * ExtractionDocument
 *
 * One extraction run: what produced it, what it yielded, and its text.
 */
export type ExtractionDocument = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Origin
     */
    origin: string;
    /**
     * Droprelativepath
     */
    dropRelativePath?: string | null;
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Bytesize
     */
    byteSize: number;
    /**
     * Layout
     */
    layout: string;
    /**
     * Itemcount
     */
    itemCount: number;
    /**
     * Artifactcount
     */
    artifactCount: number;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Promptversion
     */
    promptVersion?: number | null;
    /**
     * Prompthash
     */
    promptHash?: string | null;
    /**
     * Documenttext
     */
    documentText: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * ExtractionPrompt
 *
 * One document kind's active, complete prompt text.
 */
export type ExtractionPrompt = {
    /**
     * Kind
     */
    kind: 'adr' | 'action-item' | 'topic';
    /**
     * Prompttext
     */
    promptText: string;
};

/**
 * ExtractionPromptsResponse
 */
export type ExtractionPromptsResponse = {
    /**
     * Prompts
     */
    prompts: Array<ExtractionPrompt>;
};

/**
 * FeedItem
 *
 * One ranked moment, exactly the fields the story's AC enumerates.
 *
 * Deliberately no `score`: the acceptance criteria enumerate the card's
 * fields, and a number the client cannot explain is not one of them. The
 * ordered ``reasons`` are the explanation, and they are what story 10.5
 * renders.
 */
export type FeedItem = {
    /**
     * Momentid
     */
    momentId: string;
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Meetingtitle
     */
    meetingTitle?: string | null;
    /**
     * Startedat
     */
    startedAt: string;
    /**
     * Startedatprecision
     */
    startedAtPrecision: string;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Endms
     */
    endMs: number;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Hasrecording
     */
    hasRecording: boolean;
    /**
     * Sourcedeeplink
     */
    sourceDeepLink?: string | null;
    /**
     * Screenshotid
     */
    screenshotId?: string | null;
    /**
     * Viewtype
     */
    viewType?: 'slide' | 'ui-screen' | 'participant-gallery' | null;
    /**
     * Preview
     */
    preview?: string | null;
    /**
     * Threads
     */
    threads: Array<FeedThread>;
    /**
     * Reasons
     */
    reasons: Array<FeedReason>;
};

/**
 * FeedReason
 *
 * Why this moment is on the feed, in the order that decided its score.
 *
 * ``ref`` is the id of the row the reason came from — an artifact, a ranking
 * signal, a thread — so a card can link to its own evidence. ``at`` is the
 * time the reason is about (a due date, a meeting start, a publication),
 * never "now". Both are optional because not every reason has one.
 */
export type FeedReason = {
    /**
     * Kind
     */
    kind: 'action-item' | 'adr' | 'decision' | 'story' | 'requirement' | 'bug-fix' | 'change-request' | 'due' | 'risk' | 'question' | 'recency' | 'published' | 'thread';
    /**
     * Label
     */
    label: string;
    /**
     * Ref
     */
    ref?: string | null;
    /**
     * At
     */
    at?: string | null;
};

/**
 * FeedThread
 *
 * One thread chip on the card.
 *
 * ``color_ordinal`` is the server-owned immutable ordinal story 10.3
 * allocates; the client maps it to a hue and never invents one. Migration
 * 0017 now guarantees a positive bigint for every persisted thread. The
 * optional type preserves the scorer's plain-fact boundary for malformed or
 * legacy input; the running schema's query-to-wire path is non-null.
 */
export type FeedThread = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Colorordinal
     */
    colorOrdinal?: number | null;
};

/**
 * FramesView
 */
export type FramesView = {
    /**
     * Intervalseconds
     */
    intervalSeconds: number;
    /**
     * Jpegquality
     */
    jpegQuality: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Config-derived service identity (serialized camelCase at the API boundary).
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Service
     */
    service: string;
    /**
     * Configversion
     */
    configVersion: number;
};

/**
 * IngestRequest
 */
export type IngestRequest = {
    /**
     * Droppath
     */
    dropPath: string;
};

/**
 * IngestResult
 */
export type IngestResult = {
    /**
     * Jobid
     */
    jobId: string;
};

/**
 * JobEvent
 *
 * One streamed event.
 *
 * ``event`` repeats the SSE event name inside the payload. That is not
 * redundancy for its own sake: the generated TypeScript client yields event
 * *data* without the name attached, so carrying it makes the payload
 * dispatchable on its own and a captured stream self-describing.
 */
export type JobEvent = {
    /**
     * Event
     */
    event: 'job.stage' | 'job.done' | 'job.error';
    /**
     * Jobid
     */
    jobId: string;
    /**
     * Jobstatus
     */
    jobStatus: string;
    /**
     * Viewable
     */
    viewable: boolean;
    /**
     * Stage
     */
    stage?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * JobResponse
 */
export type JobResponse = {
    /**
     * Jobid
     */
    jobId: string;
    /**
     * Status
     */
    status: string;
    /**
     * Sourceid
     */
    sourceId: string;
    /**
     * Droppath
     */
    dropPath: string | null;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Stages
     */
    stages: Array<JobStage>;
};

/**
 * JobStage
 */
export type JobStage = {
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * LlmRoleStatus
 */
export type LlmRoleStatus = {
    /**
     * Role
     */
    role: string;
    /**
     * Model
     */
    model: string;
    /**
     * Fallback
     */
    fallback?: string | null;
    /**
     * Provider
     */
    provider?: string | null;
    /**
     * Keystate
     */
    keyState: 'present' | 'missing' | 'invalid' | 'not-required' | 'unknown';
    /**
     * State
     */
    state: 'ok' | 'degraded';
    /**
     * Detail
     */
    detail: string;
    /**
     * Remediation
     */
    remediation?: string | null;
    /**
     * Source
     */
    source: 'selection' | 'file-default' | 'unknown';
    /**
     * Defaultbinding
     */
    defaultBinding: string;
    /**
     * Filebinding
     */
    fileBinding: string;
    /**
     * Selected
     */
    selected?: string | null;
    /**
     * Staleselection
     */
    staleSelection?: string | null;
    /**
     * Stalereason
     */
    staleReason?: string | null;
    /**
     * Observedby
     */
    observedBy?: string;
    /**
     * Servedby
     */
    servedBy?: string | null;
    /**
     * Attribution
     */
    attribution: string;
};

/**
 * LlmRoleView
 *
 * One ``llm.roles.<role>`` binding, endpoint resolved, prompts included.
 *
 * ``endpoint`` is where the primary model's calls actually go: the role's
 * own ``base_url`` override when set, else the provider's ``providers.*``
 * entry — resolved here so the page shows the effective endpoint rather
 * than making the reader re-derive the override rule. ``fallback_endpoint``
 * is only ever the role's explicit ``fallback_base_url``: an absent value
 * means the fallback resolves through ``providers`` on its own (the
 * config.py rule that a fallback never inherits the primary's host).
 */
export type LlmRoleView = {
    /**
     * Role
     */
    role: string;
    /**
     * Model
     */
    model: string;
    /**
     * Fallback
     */
    fallback?: string | null;
    /**
     * Provider
     */
    provider?: string | null;
    /**
     * Endpoint
     */
    endpoint?: string | null;
    /**
     * Fallbackendpoint
     */
    fallbackEndpoint?: string | null;
    /**
     * Timeoutseconds
     */
    timeoutSeconds?: number | null;
    /**
     * Numctx
     */
    numCtx?: number | null;
    /**
     * Archsummaryprompt
     */
    archSummaryPrompt?: string | null;
    /**
     * Actionitemsprompt
     */
    actionItemsPrompt?: string | null;
};

/**
 * MeetingDrilldownResponse
 *
 * The whole meeting's evidence: header, series, full transcript.
 */
export type MeetingDrilldownResponse = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Hasrecording
     */
    hasRecording: boolean;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Startedat
     */
    startedAt: string;
    /**
     * Startedatprecision
     */
    startedAtPrecision: string;
    /**
     * Sourcedeeplink
     */
    sourceDeepLink?: string | null;
    /**
     * Screenshots
     */
    screenshots: Array<DrilldownScreenshot>;
    /**
     * Segments
     */
    segments: Array<DrilldownSegment>;
};

/**
 * MeetingExtractionDocumentsResponse
 */
export type MeetingExtractionDocumentsResponse = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Documents
     */
    documents: Array<ExtractionDocument>;
};

/**
 * MeetingListItem
 *
 * One ingestion, as the meetings view renders it.
 */
export type MeetingListItem = {
    /**
     * Jobid
     */
    jobId: string;
    /**
     * Meetingid
     */
    meetingId?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Sourceid
     */
    sourceId: string;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Startedat
     */
    startedAt?: string | null;
    /**
     * Startedatprecision
     */
    startedAtPrecision?: string | null;
    /**
     * Hasrecording
     */
    hasRecording?: boolean | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Stages
     */
    stages: Array<JobStage>;
    /**
     * Viewable
     */
    viewable: boolean;
    /**
     * Durationms
     */
    durationMs?: number | null;
    /**
     * Posterscreenshotid
     */
    posterScreenshotId?: string | null;
    /**
     * Posterscreenshotpath
     */
    posterScreenshotPath?: string | null;
    /**
     * Momentcount
     */
    momentCount?: number;
    /**
     * Screenshotcount
     */
    screenshotCount?: number;
    /**
     * Artifactcount
     */
    artifactCount?: number;
    /**
     * Participantcount
     */
    participantCount?: number;
};

/**
 * MeetingMomentsResponse
 *
 * The meeting header plus its live moments, in `start_ms, id` order.
 */
export type MeetingMomentsResponse = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Hasrecording
     */
    hasRecording: boolean;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Startedat
     */
    startedAt: string;
    /**
     * Startedatprecision
     */
    startedAtPrecision: string;
    /**
     * Moments
     */
    moments: Array<MomentListItem>;
};

/**
 * MeetingProjectAssignment
 */
export type MeetingProjectAssignment = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Projectid
     */
    projectId: string | null;
};

/**
 * MeetingSeriesAssignment
 */
export type MeetingSeriesAssignment = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Seriesid
     */
    seriesId: string | null;
};

/**
 * MeetingSpeakersResponse
 *
 * Every speaker tag of one meeting, talk time descending.
 */
export type MeetingSpeakersResponse = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Speakers
     */
    speakers: Array<SpeakerTag>;
};

/**
 * MeetingsResponse
 */
export type MeetingsResponse = {
    /**
     * Meetings
     */
    meetings: Array<MeetingListItem>;
};

/**
 * MeetingsTimeline
 */
export type MeetingsTimeline = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Colorordinal
     */
    colorOrdinal: number;
    /**
     * Windowfrom
     */
    windowFrom?: string | null;
    /**
     * Windowto
     */
    windowTo?: string | null;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Meetingcount
     */
    meetingCount: number;
    /**
     * Momentcount
     */
    momentCount: number;
    /**
     * Level
     */
    level: 'meetings';
    /**
     * Meetings
     */
    meetings: Array<TimelineMeeting>;
};

/**
 * MeilisearchView
 */
export type MeilisearchView = {
    /**
     * Url
     */
    url: string;
};

/**
 * MergeParticipantsRequest
 */
export type MergeParticipantsRequest = {
    /**
     * Intoparticipantid
     */
    intoParticipantId: string;
};

/**
 * ModelSettingsResponse
 */
export type ModelSettingsResponse = {
    /**
     * Roles
     */
    roles: Array<RoleSelectionView>;
};

/**
 * MomentArtifact
 *
 * One extracted artifact, as the right rail renders it.
 *
 * `id`/`kind`/`state`/`title`/`body` are 2.2's frozen wire fields, unchanged
 * in name and meaning. The three publish fields are story 4.3's addition:
 * all `None` for an `extracted` or `approved` row, all set together once a
 * row becomes `published` — there is no state where only some are set.
 */
export type MomentArtifact = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'action-item' | 'adr' | 'decision' | 'story' | 'requirement' | 'bug-fix' | 'change-request';
    /**
     * State
     */
    state: 'extracted' | 'approved' | 'published';
    /**
     * Title
     */
    title: string;
    /**
     * Body
     */
    body: string;
    /**
     * Publishedat
     */
    publishedAt?: string | null;
    /**
     * Publishrelativepath
     */
    publishRelativePath?: string | null;
    /**
     * Publishcommitsha
     */
    publishCommitSha?: string | null;
};

/**
 * MomentDetail
 *
 * One moment: the evidence CAP-4's view renders.
 */
export type MomentDetail = {
    /**
     * Momentid
     */
    momentId: string;
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Meetingtitle
     */
    meetingTitle?: string | null;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Hasrecording
     */
    hasRecording: boolean;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Endms
     */
    endMs: number;
    /**
     * Startedat
     */
    startedAt: string;
    /**
     * Startedatprecision
     */
    startedAtPrecision: string;
    /**
     * Screenshotid
     */
    screenshotId?: string | null;
    /**
     * Screenshotpath
     */
    screenshotPath?: string | null;
    /**
     * Sourcedeeplink
     */
    sourceDeepLink?: string | null;
    /**
     * Superseded
     */
    superseded: boolean;
    /**
     * Segments
     */
    segments: Array<MomentSegment>;
    /**
     * Artifacts
     */
    artifacts: Array<MomentArtifact>;
};

/**
 * MomentListItem
 *
 * One live moment, as the meeting's moments list renders it.
 *
 * Field names and types reuse the `SearchHit` vocabulary (`api/search.py`)
 * wherever the two describe the same column, so the generated TS client
 * keeps one spelling per column.
 */
export type MomentListItem = {
    /**
     * Momentid
     */
    momentId: string;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Endms
     */
    endMs: number;
    /**
     * Startedat
     */
    startedAt: string;
    /**
     * Startedatprecision
     */
    startedAtPrecision: string;
    /**
     * Screenshotid
     */
    screenshotId?: string | null;
    /**
     * Sourcedeeplink
     */
    sourceDeepLink?: string | null;
    /**
     * Segmentcount
     */
    segmentCount: number;
    /**
     * Preview
     */
    preview?: string | null;
};

/**
 * MomentSegment
 *
 * One covered transcript segment, exactly as stored — an overhanging
 * `end_ms` is the segment's own reading, not an error to clip.
 */
export type MomentSegment = {
    /**
     * Startms
     */
    startMs: number;
    /**
     * Endms
     */
    endMs: number;
    /**
     * Speakerlabel
     */
    speakerLabel: string;
    /**
     * Speakerresolution
     */
    speakerResolution?: string | null;
    /**
     * Participantid
     */
    participantId?: string | null;
    /**
     * Text
     */
    text: string;
};

/**
 * MomentsFeedResponse
 *
 * The page, its filtered size, and its selected-corpus denominator.
 *
 * ``total`` counts the rows that survived reason validation — never the raw
 * candidate scan — and all item filters. ``corpus_total`` counts the same
 * validated selected corpus before the meeting, thread, and kind filters, so
 * the client never derives that denominator or makes another HTTP request.
 *
 * Every request is a live ranking, not a snapshot shared with another page.
 * The route clamps an offset beyond the filtered set to its end, so the
 * in-response invariant `offset + len(items) <= total` always holds.
 */
export type MomentsFeedResponse = {
    /**
     * Items
     */
    items: Array<FeedItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Corpustotal
     */
    corpusTotal: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * MomentsTimeline
 */
export type MomentsTimeline = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Colorordinal
     */
    colorOrdinal: number;
    /**
     * Windowfrom
     */
    windowFrom?: string | null;
    /**
     * Windowto
     */
    windowTo?: string | null;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Meetingcount
     */
    meetingCount: number;
    /**
     * Momentcount
     */
    momentCount: number;
    /**
     * Level
     */
    level: 'moments';
    /**
     * Truncated
     */
    truncated: boolean;
    /**
     * Moments
     */
    moments: Array<TimelineMoment>;
};

/**
 * MomentsView
 */
export type MomentsView = {
    /**
     * Gapseconds
     */
    gapSeconds: number;
    /**
     * Maxdurationms
     */
    maxDurationMs: number;
};

/**
 * Neo4jView
 */
export type Neo4jView = {
    /**
     * Uri
     */
    uri: string;
    /**
     * User
     */
    user: string;
};

/**
 * ObservedBy
 *
 * Whose reading the whole payload is (AD-10 as amended, AD-18).
 *
 * Named once at the top so no consumer has to assemble the attribution from
 * the rows, and so a surface that renders only a summary still has the one
 * fact it may not omit: which process answered, and out of which file.
 */
export type ObservedBy = {
    /**
     * Process
     */
    process: string;
    /**
     * Configpath
     */
    configPath: string;
    /**
     * Configloadedat
     */
    configLoadedAt?: string | null;
    /**
     * Catalognote
     */
    catalogNote?: string;
    /**
     * Selectionnote
     */
    selectionNote?: string;
};

/**
 * OcrView
 */
export type OcrView = {
    /**
     * Engine
     */
    engine: string;
    /**
     * Fallback
     */
    fallback?: string | null;
};

/**
 * ParticipantRow
 *
 * One `participant` row, canonical or merged-away.
 *
 * `mergedIntoParticipantId` is set exactly when this row's `identityKey` is
 * itself an alias key elsewhere — curators see merge history, not just the
 * current canonical set (`GET /participants`'s contract).
 */
export type ParticipantRow = {
    /**
     * Id
     */
    id: string;
    /**
     * Identitykey
     */
    identityKey: string;
    /**
     * Displayname
     */
    displayName: string;
    /**
     * Normalizedname
     */
    normalizedName: string;
    /**
     * Mergedintoparticipantid
     */
    mergedIntoParticipantId?: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * PipelineView
 */
export type PipelineView = {
    frames: FramesView;
    screens: ScreensView;
    align: AlignView;
    moments: MomentsView;
};

/**
 * PostgresView
 *
 * Coordinates only — the password lives in .env and never serializes.
 */
export type PostgresView = {
    /**
     * Host
     */
    host: string;
    /**
     * Port
     */
    port: number;
    /**
     * Database
     */
    database: string;
    /**
     * User
     */
    user: string;
};

/**
 * ProbeCaptions
 */
export type ProbeCaptions = {
    /**
     * Kind
     */
    kind: string;
    /**
     * Language
     */
    language: string;
};

/**
 * ProbeRequest
 *
 * ``POST /acquisitions/probe`` takes a URL and only a URL.
 */
export type ProbeRequest = {
    /**
     * Url
     */
    url: string;
};

/**
 * ProbeResult
 */
export type ProbeResult = {
    /**
     * Title
     */
    title: string;
    /**
     * Durationms
     */
    durationMs: number;
    captions: ProbeCaptions | null;
    /**
     * Sourceid
     */
    sourceId: string;
};

/**
 * ProblemDetails
 *
 * OpenAPI shape of an RFC 9457 error body (extension members allowed).
 */
export type ProblemDetails = {
    /**
     * Type
     */
    type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Status
     */
    status: number;
    /**
     * Detail
     */
    detail: string;
    [key: string]: unknown;
};

/**
 * ProductRow
 */
export type ProductRow = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * ProjectListRow
 *
 * A project plus its assigned meetings, ordered by meeting start.
 */
export type ProjectListRow = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Productid
     */
    productId: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    /**
     * Meetingids
     */
    meetingIds: Array<string>;
};

/**
 * ProjectRow
 */
export type ProjectRow = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Productid
     */
    productId: string | null;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * ProjectionsView
 */
export type ProjectionsView = {
    chunking: ChunkingView;
    /**
     * Embedbatchsize
     */
    embedBatchSize: number;
    momentsIndex: SearchIndexView;
    chunksIndex: SearchIndexView;
    /**
     * Synonyms
     */
    synonyms: {
        [key: string]: Array<string>;
    };
};

/**
 * ProviderStatus
 *
 * One configured provider's key validity (story 8.2a, FR39).
 *
 * The four fields the story names — ``provider``, ``keyState``, ``detail``,
 * ``remediation`` — plus two that keep the row honest. ``state`` is carried
 * rather than inferred from ``remediation is not None``: a reader that
 * derives health from the presence of prose is one wording change away from
 * reporting the wrong thing. ``observedBy`` names the process whose ``.env``
 * and ``config.yaml`` snapshot produced the reading, because a key state is
 * as process-local as a binding is (AD-10 as amended).
 *
 * Probed through the provider's free model-list endpoint only, behind the
 * same cache the role rows use — never a completion, and never a second
 * request for a provider a role already probed at the same endpoint.
 */
export type ProviderStatus = {
    /**
     * Provider
     */
    provider: string;
    /**
     * Keystate
     */
    keyState: 'present' | 'missing' | 'invalid' | 'not-required' | 'unknown';
    /**
     * Detail
     */
    detail: string;
    /**
     * Remediation
     */
    remediation?: string | null;
    /**
     * State
     */
    state: 'ok' | 'degraded';
    /**
     * Observedby
     */
    observedBy?: string;
};

/**
 * RelatedSubject
 */
export type RelatedSubject = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Colorordinal
     */
    colorOrdinal: number;
    /**
     * Sharedmoments
     */
    sharedMoments: number;
};

/**
 * RenameParticipantRequest
 */
export type RenameParticipantRequest = {
    /**
     * Displayname
     */
    displayName: string;
};

/**
 * RoleSelectionRequest
 */
export type RoleSelectionRequest = {
    /**
     * Binding
     */
    binding: string;
};

/**
 * RoleSelectionView
 *
 * One role's catalog, the binding in force, and how it was arrived at.
 */
export type RoleSelectionView = {
    /**
     * Role
     */
    role: string;
    /**
     * Catalog
     */
    catalog: Array<CatalogEntryView>;
    /**
     * Default
     */
    default: string;
    /**
     * Filebinding
     */
    fileBinding: string;
    /**
     * Selected
     */
    selected: string | null;
    /**
     * Effectivebinding
     */
    effectiveBinding: string;
    /**
     * Provider
     */
    provider: string | null;
    /**
     * Source
     */
    source: string;
    /**
     * Staleselection
     */
    staleSelection: string | null;
    /**
     * Stalereason
     */
    staleReason: string | null;
};

/**
 * RouteModel
 *
 * What the router decided and what each leg produced.
 *
 * On the wire rather than only in the log: an operator comparing two answers
 * to the same question has to be able to see that one was traversed and the
 * other was not, and story 3.4 shows "answered from N moments" without a
 * second round trip.
 */
export type RouteModel = {
    /**
     * Template
     */
    template?: string | null;
    /**
     * Anchorresolved
     */
    anchorResolved?: boolean | null;
    /**
     * Traversaloutcome
     */
    traversalOutcome?: string;
    /**
     * Fallbackreason
     */
    fallbackReason?: string | null;
    /**
     * Searchhits
     */
    searchHits: number;
    /**
     * Traversalrows
     */
    traversalRows: number;
    /**
     * Traversaltruncated
     */
    traversalTruncated?: boolean;
    /**
     * Retrieved
     */
    retrieved: number;
};

/**
 * ScreensView
 *
 * Every threshold the screens stage compares against (AD-10).
 */
export type ScreensView = {
    /**
     * Analysiswidth
     */
    analysisWidth: number;
    /**
     * Pixeldiffthreshold
     */
    pixelDiffThreshold: number;
    /**
     * Whitepixellevel
     */
    whitePixelLevel: number;
    /**
     * Changethreshold
     */
    changeThreshold: number;
    /**
     * Settlethreshold
     */
    settleThreshold: number;
    /**
     * Settletextgrowthratio
     */
    settleTextGrowthRatio: number;
    /**
     * Settletimeoutseconds
     */
    settleTimeoutSeconds: number;
    /**
     * Cropsurveyframes
     */
    cropSurveyFrames: number;
    /**
     * Cropcolumnwhitemax
     */
    cropColumnWhiteMax: number;
    /**
     * Cropminregionwidth
     */
    cropMinRegionWidth: number;
    /**
     * Croprowstaticrangemax
     */
    cropRowStaticRangeMax: number;
    /**
     * Cropmaxbottomstrip
     */
    cropMaxBottomStrip: number;
    /**
     * Cameramaxwhitefraction
     */
    cameraMaxWhiteFraction: number;
    /**
     * Cameraminsaturation
     */
    cameraMinSaturation: number;
    /**
     * Lineagethreshold
     */
    lineageThreshold: number;
    /**
     * Minsignaturetokens
     */
    minSignatureTokens: number;
    /**
     * Gallerymaxblocks
     */
    galleryMaxBlocks: number;
    /**
     * Gallerymaxtextdensity
     */
    galleryMaxTextDensity: number;
    /**
     * Slideminblockheight
     */
    slideMinBlockHeight: number;
    /**
     * Slidemaxblocks
     */
    slideMaxBlocks: number;
};

/**
 * SearchHit
 *
 * One search result, in the AD-15 citation shape plus its snippet.
 */
export type SearchHit = {
    /**
     * Momentid
     */
    momentId: string;
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Meetingtitle
     */
    meetingTitle?: string | null;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Endms
     */
    endMs: number;
    /**
     * Startedat
     */
    startedAt?: string | null;
    /**
     * Startedatprecision
     */
    startedAtPrecision?: string | null;
    /**
     * Screenshotid
     */
    screenshotId?: string | null;
    /**
     * Sourcedeeplink
     */
    sourceDeepLink?: string | null;
    /**
     * Hasrecording
     */
    hasRecording: boolean;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Snippet
     */
    snippet: Array<SnippetRunModel>;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Artifactid
     *
     * The published artifact's own id when this hit is an artifact rather than a moment (story 4.4); null on a moment hit.
     */
    artifactId?: string | null;
    /**
     * Artifactkind
     *
     * The artifact's kind ('adr' or 'action-item'); null on a moment hit.
     */
    artifactKind?: string | null;
    /**
     * Artifacttitle
     *
     * The artifact's title; null on a moment hit.
     */
    artifactTitle?: string | null;
};

/**
 * SearchIndexView
 */
export type SearchIndexView = {
    /**
     * Searchableattributes
     */
    searchableAttributes: Array<string>;
    /**
     * Filterableattributes
     */
    filterableAttributes: Array<string>;
    /**
     * Sortableattributes
     */
    sortableAttributes: Array<string>;
    /**
     * Rankingrules
     */
    rankingRules: Array<string>;
};

/**
 * SearchKnobsView
 */
export type SearchKnobsView = {
    /**
     * Defaultlimit
     */
    defaultLimit: number;
    /**
     * Maxlimit
     */
    maxLimit: number;
    /**
     * Semanticratio
     */
    semanticRatio: number;
    /**
     * Croplength
     */
    cropLength: number;
    /**
     * Semanticscorefloor
     */
    semanticScoreFloor: number;
};

/**
 * SearchResponse
 */
export type SearchResponse = {
    /**
     * Query
     */
    query: string;
    /**
     * Ranking
     */
    ranking: 'hybrid' | 'keyword';
    /**
     * Hits
     */
    hits: Array<SearchHit>;
    /**
     * Estimatedtotal
     */
    estimatedTotal: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Indexmissing
     */
    indexMissing?: boolean;
};

/**
 * SeriesListRow
 *
 * A series plus its assigned meetings, ordered by meeting start.
 */
export type SeriesListRow = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    /**
     * Meetingids
     */
    meetingIds: Array<string>;
};

/**
 * SeriesRow
 */
export type SeriesRow = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * SnippetRunModel
 *
 * One run of snippet text — matched or not.
 *
 * Structured rather than marked-up on purpose. The web app wraps the
 * highlighted runs itself and never receives markup it would have to trust,
 * which is the AD-15 principle applied to snippets: consumers render from
 * the array, they do not parse a string.
 */
export type SnippetRunModel = {
    /**
     * Text
     */
    text: string;
    /**
     * Highlighted
     */
    highlighted: boolean;
};

/**
 * SpeakerAssignmentResponse
 *
 * What was recorded, and what was re-armed to act on it.
 *
 * Deliberately reports the *persisted* facts rather than predicting the
 * attribution the rerun will write: ``align`` decides that, and a response
 * claiming it in advance would be guessing, on the one story that exists to
 * stop guessing (AD-13). ``participantId``/``displayName`` are the alias
 * target — both null for ``unresolved``, which stores no row at all.
 */
export type SpeakerAssignmentResponse = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Speakerlabel
     */
    speakerLabel: string;
    /**
     * Participantid
     */
    participantId: string | null;
    /**
     * Displayname
     */
    displayName: string | null;
    /**
     * Jobid
     */
    jobId: string;
    /**
     * Rearmedstages
     */
    rearmedStages: Array<string>;
    /**
     * Acceptedwhileunviewable
     *
     * Whether this PUT was accepted while meeting evidence was unviewable.
     */
    acceptedWhileUnviewable: boolean;
    /**
     * Previousjobstatus
     *
     * The job status observed before this assignment re-armed it.
     */
    previousJobStatus: 'queued' | 'done' | 'failed';
};

/**
 * SpeakerTag
 *
 * One voice in one meeting, as the transcript labelled it.
 *
 * ``speakerLabel`` is ``transcript_segment.speaker_label`` verbatim — the
 * diarizer's ``SPEAKER_00``, or the source's ``Goeke, Timothy`` — never a
 * normalized or prettified form, and never replaced by the participant's
 * display name: the label is what the reader has to recognize in the
 * transcript beside it.
 *
 * ``participantId``/``displayName`` are populated exactly when
 * ``transcript_segment.participant_id`` is, which migration 0005 constrains
 * to ``speakerResolution == 'resolved'``. A ``placeholder``, ``unresolved``
 * or ``ambiguous`` tag is listed with both null: an absent attribution, not
 * a guessed one (AD-13).
 */
export type SpeakerTag = {
    /**
     * Speakerlabel
     */
    speakerLabel: string;
    /**
     * Speakerresolution
     */
    speakerResolution: string;
    /**
     * Participantid
     */
    participantId: string | null;
    /**
     * Displayname
     */
    displayName: string | null;
    /**
     * Talktimems
     */
    talkTimeMs: number;
    /**
     * Segmentcount
     */
    segmentCount: number;
    /**
     * Sampleoffsetsms
     */
    sampleOffsetsMs: Array<number>;
};

/**
 * StatusResponse
 */
export type StatusResponse = {
    /**
     * Generatedat
     */
    generatedAt: string;
    /**
     * Overall
     */
    overall: 'ok' | 'degraded';
    observedBy: ObservedBy;
    api: ComponentStatus;
    /**
     * Stores
     */
    stores: Array<ComponentStatus>;
    /**
     * Providers
     */
    providers: Array<ProviderStatus>;
    /**
     * Llmroles
     */
    llmRoles: Array<LlmRoleStatus>;
    worker: WorkerStatus;
};

/**
 * StoresView
 */
export type StoresView = {
    postgres: PostgresView;
    neo4j: Neo4jView;
    meilisearch: MeilisearchView;
};

/**
 * SttView
 */
export type SttView = {
    /**
     * Engine
     */
    engine: string;
    /**
     * Model
     */
    model: string;
};

/**
 * SubjectCandidate
 *
 * An adjacent subject the typed wording could have meant.
 */
export type SubjectCandidate = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Colorordinal
     */
    colorOrdinal: number;
    /**
     * Meetingcount
     */
    meetingCount: number;
    /**
     * Spandays
     */
    spanDays: number;
};

/**
 * SubjectReach
 *
 * How far a subject runs, which is the whole basis for offering it.
 *
 * Both numbers are shown to the reader rather than only ranked on: "9
 * meetings over 118 days" is what makes a suggestion a considered choice
 * instead of a button whose label is the only thing known about it.
 */
export type SubjectReach = {
    /**
     * Meetingcount
     */
    meetingCount: number;
    /**
     * Spandays
     */
    spanDays: number;
    /**
     * Firstmentionat
     */
    firstMentionAt: string;
    /**
     * Lastmentionat
     */
    lastMentionAt: string;
};

/**
 * SuggestedSubject
 */
export type SuggestedSubject = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Colorordinal
     */
    colorOrdinal: number;
    /**
     * Mentioncount
     */
    mentionCount: number;
    reach: SubjectReach;
};

/**
 * SuggestionsResponse
 *
 * The empty state's offer, with the band it was drawn from.
 *
 * The band travels with the answer because an empty list means something
 * specific — no subject in this corpus recurs across meetings for long enough
 * to be worth tracing — and a client that cannot see the bounds would have to
 * render that as a blank.
 */
export type SuggestionsResponse = {
    /**
     * Subjects
     */
    subjects: Array<SuggestedSubject>;
    /**
     * Minmeetings
     */
    minMeetings: number;
    /**
     * Maxmeetings
     */
    maxMeetings: number;
    /**
     * Minspandays
     */
    minSpanDays: number;
};

/**
 * ThreadSummary
 *
 * One thread as the Threads view lists it.
 *
 * Every instant is an RFC 3339 UTC string the server derived, never a
 * timestamp the client is expected to reassemble from an offset.
 */
export type ThreadSummary = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Meetingcount
     */
    meetingCount: number;
    /**
     * Firstmentionat
     */
    firstMentionAt: string;
    /**
     * Lastmentionat
     */
    lastMentionAt: string;
    /**
     * Colorordinal
     */
    colorOrdinal: number;
};

/**
 * ThreadTrace
 *
 * One subject, traced across every meeting where it surfaced.
 *
 * **`mode` is the closed set; `completenessNote` is the prose.** Both are
 * carried because a client that inferred completeness from the wording would
 * be one edit away from presenting a sample as a full history — the same
 * unverified-absence failure as claiming no recording exists, in the one view
 * whose entire claim is that it shows the corpus's true shape (AD-18).
 */
export type ThreadTrace = {
    /**
     * Mode
     */
    mode: 'exhaustive' | 'sample';
    /**
     * Label
     */
    label: string;
    /**
     * Threadid
     */
    threadId?: string | null;
    /**
     * Colorordinal
     */
    colorOrdinal?: number | null;
    /**
     * Resolvedfrom
     */
    resolvedFrom?: string | null;
    /**
     * Ranking
     */
    ranking?: 'hybrid' | 'keyword' | null;
    /**
     * Complete
     */
    complete: boolean;
    /**
     * Completenessnote
     */
    completenessNote: string;
    /**
     * Permeetinglimit
     */
    perMeetingLimit: number;
    span?: TraceSpan | null;
    counts: TraceCounts;
    /**
     * Candidates
     */
    candidates: Array<SubjectCandidate>;
    /**
     * Relatedsubjects
     */
    relatedSubjects: Array<RelatedSubject>;
    /**
     * Stops
     */
    stops: Array<TraceStop>;
};

/**
 * ThreadsResponse
 */
export type ThreadsResponse = {
    /**
     * Threads
     */
    threads: Array<ThreadSummary>;
};

/**
 * TimelineArtifact
 */
export type TimelineArtifact = {
    /**
     * Artifactid
     */
    artifactId: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * State
     */
    state: string;
    /**
     * Title
     */
    title: string;
};

/**
 * TimelineBand
 *
 * One bucket of the density strip. Half-open `[startAt, endAt)`, except
 * the band's last bucket, which is closed on the window's own end.
 */
export type TimelineBand = {
    /**
     * Startat
     */
    startAt: string;
    /**
     * Endat
     */
    endAt: string;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Meetingcount
     */
    meetingCount: number;
};

/**
 * TimelineEvidence
 *
 * The moments tier plus what backs it.
 *
 * `recordingMediaId` is the meeting id: `meeting_media` is keyed by
 * `meeting_id` (migration 0002), so the meeting id *is* the recording's
 * media id. It is NULL when the meeting has no recording, so a client never
 * offers replay it cannot get bytes for.
 */
export type TimelineEvidence = {
    /**
     * Momentid
     */
    momentId: string;
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Title
     */
    title: string;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Occurredat
     *
     * Evidence start and seek position, derived from moment.start_ms. Window membership is selected by the topic mention anchor, so this value may fall outside the requested window.
     */
    occurredAt: string;
    /**
     * Occurredatprecision
     */
    occurredAtPrecision: string;
    /**
     * Speakers
     */
    speakers: Array<string>;
    /**
     * Screenshotid
     */
    screenshotId?: string | null;
    /**
     * Excerpt
     */
    excerpt?: string | null;
    /**
     * Artifacts
     */
    artifacts: Array<TimelineArtifact>;
    /**
     * Hasrecording
     */
    hasRecording: boolean;
    /**
     * Recordingmediaid
     */
    recordingMediaId?: string | null;
};

/**
 * TimelineMeeting
 */
export type TimelineMeeting = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Hasrecording
     */
    hasRecording: boolean;
    /**
     * Occurredat
     */
    occurredAt: string;
    /**
     * Lastoccurredat
     */
    lastOccurredAt: string;
    /**
     * Occurredatprecision
     */
    occurredAtPrecision: string;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Momentcount
     */
    momentCount: number;
    /**
     * Topics
     */
    topics: Array<TimelineTopic>;
};

/**
 * TimelineMoment
 *
 * The moments tier, exactly. No excerpt, no artifacts, no media beyond
 * the opaque screenshot id — those are the evidence tier's.
 */
export type TimelineMoment = {
    /**
     * Momentid
     */
    momentId: string;
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Title
     */
    title: string;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Occurredat
     *
     * Evidence start and seek position, derived from moment.start_ms. Window membership is selected by the topic mention anchor, so this value may fall outside the requested window.
     */
    occurredAt: string;
    /**
     * Occurredatprecision
     */
    occurredAtPrecision: string;
    /**
     * Speakers
     */
    speakers: Array<string>;
    /**
     * Screenshotid
     */
    screenshotId?: string | null;
};

/**
 * TimelineTopic
 *
 * One of the thread's topics as a meeting carries it, with the leg of
 * story 10.2's rule that attached it.
 */
export type TimelineTopic = {
    /**
     * Topicid
     */
    topicId: string;
    /**
     * Name
     */
    name: string;
    /**
     * Linkedby
     */
    linkedBy: string;
};

/**
 * TraceCounts
 */
export type TraceCounts = {
    /**
     * Stops
     */
    stops: number;
    /**
     * Momentsquoted
     */
    momentsQuoted: number;
    /**
     * Mentiontotal
     */
    mentionTotal: number;
    /**
     * Meetingsmentioning
     */
    meetingsMentioning: number;
    /**
     * Withscreen
     */
    withScreen: number;
};

/**
 * TraceMoment
 *
 * One quoted moment at a stop.
 */
export type TraceMoment = {
    /**
     * Momentid
     */
    momentId: string;
    /**
     * Startms
     */
    startMs: number;
    /**
     * Occurredat
     */
    occurredAt: string;
    /**
     * Occurredatprecision
     */
    occurredAtPrecision: string;
    /**
     * Speakers
     */
    speakers: Array<string>;
    /**
     * Excerpt
     */
    excerpt?: string | null;
    /**
     * Screenshotid
     */
    screenshotId?: string | null;
};

/**
 * TraceSpan
 */
export type TraceSpan = {
    /**
     * Fromat
     */
    fromAt: string;
    /**
     * Toat
     */
    toAt: string;
    /**
     * Days
     */
    days: number;
    /**
     * Meetings
     */
    meetings: number;
};

/**
 * TraceStop
 *
 * One meeting where the subject surfaced.
 *
 * `mentionCount` and `momentCount` describe the meeting; `quotedCount` is how
 * many of them are carried in `moments`. The three are all present so a
 * reader is never shown six moments from a meeting that held forty without
 * being told which they are looking at.
 *
 * `hasRecording` and `screenCount` are carried as facts rather than as a
 * rendered sentence about them: a stop with no screens must state its reason,
 * and the reason turns on whether the absence was established (transcript-only
 * ingest) or merely observed (no capture covers these moments). A client that
 * derived the state from the presence of prose would be one wording change
 * away from claiming the wrong one (AD-18).
 */
export type TraceStop = {
    /**
     * Meetingid
     */
    meetingId: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Hasrecording
     */
    hasRecording: boolean;
    /**
     * Occurredat
     */
    occurredAt: string;
    /**
     * Lastoccurredat
     */
    lastOccurredAt: string;
    /**
     * Occurredatprecision
     */
    occurredAtPrecision: string;
    /**
     * Mentioncount
     */
    mentionCount: number;
    /**
     * Momentcount
     */
    momentCount: number;
    /**
     * Quotedcount
     */
    quotedCount: number;
    /**
     * Screencount
     */
    screenCount: number;
    /**
     * Moments
     */
    moments: Array<TraceMoment>;
};

/**
 * UploadSessionView
 */
export type UploadSessionView = {
    /**
     * Uploadsessionid
     */
    uploadSessionId: string;
    /**
     * Title
     */
    title: string;
    /**
     * Startedat
     */
    startedAt: string;
    /**
     * Corpus
     */
    corpus: string;
    /**
     * Transcriptdialect
     */
    transcriptDialect: string;
    /**
     * Suppliedby
     */
    suppliedBy: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Expiresat
     */
    expiresAt: string;
    /**
     * Files
     */
    files: Array<UploadedFileView>;
};

/**
 * UploadedFileView
 */
export type UploadedFileView = {
    /**
     * Canonical
     */
    canonical: string;
    /**
     * Originalfilename
     */
    originalFilename: string;
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Bytesize
     */
    byteSize: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkerStatus
 */
export type WorkerStatus = {
    /**
     * State
     */
    state: 'running' | 'stopped' | 'unknown';
    /**
     * Jobs
     */
    jobs: {
        [key: string]: number;
    };
    /**
     * Stagebacklog
     */
    stageBacklog: {
        [key: string]: number;
    };
    /**
     * Detail
     */
    detail: string;
    /**
     * Remediation
     */
    remediation?: string | null;
};

export type CreateIngestData = {
    body: IngestRequest;
    path?: never;
    query?: never;
    url: '/ingests';
};

export type CreateIngestErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Conflict
     */
    409: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type CreateIngestResponses = {
    /**
     * An existing job was re-queued in place rather than a new one opened — either the sourceId's only job had failed, or the drop declared `augments` and re-armed that occurrence's job so evidence the meeting lacked (a recording recovered later, or the source side's participant graph) is processed against the meeting that already exists (AD-14). The returned jobId is the existing one.
     */
    200: IngestResult;
    /**
     * Successful Response
     */
    201: IngestResult;
};

export type CreateIngestResponse = CreateIngestResponses[keyof CreateIngestResponses];

export type StreamJobEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/jobs/events';
};

export type StreamJobEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type ListMeetingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/meetings';
};

export type ListMeetingsResponses = {
    /**
     * Successful Response
     */
    200: MeetingsResponse;
};

export type ListMeetingsResponse = ListMeetingsResponses[keyof ListMeetingsResponses];

export type GetMomentsFeedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Corpus
         *
         * Scope the feed to one corpus.
         */
        corpus?: 'scripted' | 'real' | null;
        /**
         * Thread
         *
         * Only moments belonging to this thread.
         */
        thread?: string | null;
        /**
         * Meeting
         *
         * Only moments of this meeting.
         */
        meeting?: string | null;
        /**
         * Kind
         *
         * Keep only items carrying a valid reason of this kind — an artifact kind or one of due/risk/question/recency/published/thread. Applied with reason validation, before pagination.
         */
        kind?: string | null;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/moments/feed';
};

export type GetMomentsFeedErrors = {
    /**
     * `invalid-request` — a filter is not the declared type.
     */
    422: ProblemDetails;
    /**
     * `internal-error` — unexpected failure.
     */
    500: unknown;
};

export type GetMomentsFeedError = GetMomentsFeedErrors[keyof GetMomentsFeedErrors];

export type GetMomentsFeedResponses = {
    /**
     * Successful Response
     */
    200: MomentsFeedResponse;
};

export type GetMomentsFeedResponse = GetMomentsFeedResponses[keyof GetMomentsFeedResponses];

export type ListMeetingMomentsData = {
    body?: never;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/meetings/{meeting_id}/moments';
};

export type ListMeetingMomentsErrors = {
    /**
     * `not-found` — no such row; the meeting was never ingested (or the moment never minted).
     */
    404: unknown;
    /**
     * `meeting-not-viewable` — the meeting exists but an evidence stage has not settled; first ingest or augmentation is in flight. Transient: retry once ingestion settles. Carries two additive extensions beside `meetingId` (story 2.3, AD-14): `augmenting` (bool — an augmentation re-run, not a first ingest) and `jobStatus` (str — the job row's own status, e.g. `running` or `failed`).
     */
    409: unknown;
    /**
     * `invalid-request` — the route parameter is not a UUID.
     */
    422: ProblemDetails;
};

export type ListMeetingMomentsError = ListMeetingMomentsErrors[keyof ListMeetingMomentsErrors];

export type ListMeetingMomentsResponses = {
    /**
     * Successful Response
     */
    200: MeetingMomentsResponse;
};

export type ListMeetingMomentsResponse = ListMeetingMomentsResponses[keyof ListMeetingMomentsResponses];

export type GetMomentData = {
    body?: never;
    path: {
        /**
         * Moment Id
         */
        moment_id: string;
    };
    query?: never;
    url: '/moments/{moment_id}';
};

export type GetMomentErrors = {
    /**
     * `not-found` — no such row; the meeting was never ingested (or the moment never minted).
     */
    404: unknown;
    /**
     * `meeting-not-viewable` — the meeting exists but an evidence stage has not settled; first ingest or augmentation is in flight. Transient: retry once ingestion settles. Carries two additive extensions beside `meetingId` (story 2.3, AD-14): `augmenting` (bool — an augmentation re-run, not a first ingest) and `jobStatus` (str — the job row's own status, e.g. `running` or `failed`).
     */
    409: unknown;
    /**
     * `invalid-request` — the route parameter is not a UUID.
     */
    422: ProblemDetails;
};

export type GetMomentError = GetMomentErrors[keyof GetMomentErrors];

export type GetMomentResponses = {
    /**
     * Successful Response
     */
    200: MomentDetail;
};

export type GetMomentResponse = GetMomentResponses[keyof GetMomentResponses];

export type ApproveMomentArtifactsData = {
    body?: never;
    path: {
        /**
         * Moment Id
         */
        moment_id: string;
    };
    query?: never;
    url: '/moments/{moment_id}/approve';
};

export type ApproveMomentArtifactsErrors = {
    /**
     * `not-found` — no such row; the meeting was never ingested (or the moment never minted).
     */
    404: unknown;
    /**
     * `meeting-not-viewable` — the meeting exists but an evidence stage has not settled; first ingest or augmentation is in flight. Transient: retry once ingestion settles. Carries two additive extensions beside `meetingId` (story 2.3, AD-14): `augmenting` (bool — an augmentation re-run, not a first ingest) and `jobStatus` (str — the job row's own status, e.g. `running` or `failed`).
     */
    409: unknown;
    /**
     * `invalid-request` — the route parameter is not a UUID.
     */
    422: ProblemDetails;
};

export type ApproveMomentArtifactsError = ApproveMomentArtifactsErrors[keyof ApproveMomentArtifactsErrors];

export type ApproveMomentArtifactsResponses = {
    /**
     * Response Approvemomentartifacts
     *
     * Successful Response
     */
    200: Array<MomentArtifact>;
};

export type ApproveMomentArtifactsResponse = ApproveMomentArtifactsResponses[keyof ApproveMomentArtifactsResponses];

export type GetMeetingDrilldownData = {
    body?: never;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/meetings/{meeting_id}/drilldown';
};

export type GetMeetingDrilldownErrors = {
    /**
     * `not-found` — no such row; the meeting was never ingested (or the moment never minted).
     */
    404: unknown;
    /**
     * `meeting-not-viewable` — the meeting exists but an evidence stage has not settled; first ingest or augmentation is in flight. Transient: retry once ingestion settles. Carries two additive extensions beside `meetingId` (story 2.3, AD-14): `augmenting` (bool — an augmentation re-run, not a first ingest) and `jobStatus` (str — the job row's own status, e.g. `running` or `failed`).
     */
    409: unknown;
    /**
     * `invalid-request` — the route parameter is not a UUID.
     */
    422: ProblemDetails;
};

export type GetMeetingDrilldownError = GetMeetingDrilldownErrors[keyof GetMeetingDrilldownErrors];

export type GetMeetingDrilldownResponses = {
    /**
     * Successful Response
     */
    200: MeetingDrilldownResponse;
};

export type GetMeetingDrilldownResponse = GetMeetingDrilldownResponses[keyof GetMeetingDrilldownResponses];

export type SearchCorpusData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * What to search the corpus for.
         */
        q: string;
        /**
         * Limit
         */
        limit?: number | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Meetingid
         *
         * Scope the search to one meeting.
         */
        meetingId?: string | null;
        /**
         * Corpus
         *
         * Scope the search to one corpus.
         */
        corpus?: 'scripted' | 'real' | null;
    };
    url: '/search';
};

export type SearchCorpusErrors = {
    /**
     * `invalid-request` — a parameter was refused at the door rather than silently repaired.
     */
    422: unknown;
    /**
     * `embedder-unusable` — the configured embedding model answered wrongly, which is a config error rather than an outage. `search-store-unavailable` — Meilisearch could not be reached. `search-store-unusable` — Meilisearch is reachable but the query could not be run against it (no `MEILI_MASTER_KEY`, a refused query, or a document with no id).
     */
    503: unknown;
};

export type SearchCorpusResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type SearchCorpusResponse = SearchCorpusResponses[keyof SearchCorpusResponses];

export type AskCorpusData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat';
};

export type AskCorpusErrors = {
    /**
     * `no-citable-answer` — retrieval or the citation gate refused the answer, with a camelCase `reason` extension naming which (`no-evidence`, `no-citations`, `uncited-claim`, `unresolvable-marker`, `empty-answer`). No answer text and no citation is returned by any surface, including the stream, which never opens. `invalid-request` — the question was blank or past the length bound and was refused at the door.
     */
    422: unknown;
    /**
     * `binding-failed` — the selected model binding is not served by the provider endpoint. Retrying cannot repair the binding; select a served model or change the endpoint.
     */
    502: ProblemDetails;
    /**
     * The slug names what to restart. `chat-search-store-unavailable` / `chat-search-store-unusable` — Meilisearch. `chat-graph-store-unavailable` / `chat-graph-store-unusable` — Neo4j. `chat-model-unavailable` / `chat-model-unusable` — the configured `llm.roles.chat` binding and its fallback. `embedder-unusable` — the configured embedding model answered wrongly, which is a config error rather than an outage.
     */
    503: unknown;
};

export type AskCorpusError = AskCorpusErrors[keyof AskCorpusErrors];

export type AskCorpusResponses = {
    /**
     * The validated answer. Under `Accept: application/json` it is the whole `ChatResponse`; under `Accept: text/event-stream` the same answer is replayed as `chat.token`+ (payload `{event, text}`), then `chat.citations` (payload `{event, citations}` carrying the identical array), then `chat.done` (payload `{event, route}`). Concatenating every `chat.token` text reproduces `answer` exactly.
     */
    200: ChatResponse;
};

export type AskCorpusResponse = AskCorpusResponses[keyof AskCorpusResponses];

export type GetRecordingData = {
    body?: never;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/media/recordings/{meeting_id}';
};

export type GetRecordingErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Requested Range Not Satisfiable
     */
    416: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetRecordingError = GetRecordingErrors[keyof GetRecordingErrors];

export type GetRecordingResponses = {
    /**
     * The file's bytes.
     */
    200: Blob | File;
    /**
     * The requested byte range.
     */
    206: Blob | File;
};

export type GetRecordingResponse = GetRecordingResponses[keyof GetRecordingResponses];

export type GetMediaFileData = {
    body?: never;
    path: {
        /**
         * Path
         */
        path: string;
    };
    query?: never;
    url: '/media/{path}';
};

export type GetMediaFileErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Requested Range Not Satisfiable
     */
    416: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetMediaFileError = GetMediaFileErrors[keyof GetMediaFileErrors];

export type GetMediaFileResponses = {
    /**
     * The file's bytes.
     */
    200: Blob | File;
    /**
     * The requested byte range.
     */
    206: Blob | File;
};

export type GetMediaFileResponse = GetMediaFileResponses[keyof GetMediaFileResponses];

export type StartAcquisitionData = {
    body: AcquisitionRequest;
    path?: never;
    query?: never;
    url: '/acquisitions';
};

export type StartAcquisitionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Conflict
     */
    409: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
    /**
     * Service Unavailable
     */
    503: unknown;
};

export type StartAcquisitionResponses = {
    /**
     * Successful Response
     */
    202: AcquisitionAccepted;
};

export type StartAcquisitionResponse = StartAcquisitionResponses[keyof StartAcquisitionResponses];

export type ProbeAcquisitionData = {
    body: ProbeRequest;
    path?: never;
    query?: never;
    url: '/acquisitions/probe';
};

export type ProbeAcquisitionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
    /**
     * Service Unavailable
     */
    503: unknown;
};

export type ProbeAcquisitionResponses = {
    /**
     * Successful Response
     */
    200: ProbeResult;
};

export type ProbeAcquisitionResponse = ProbeAcquisitionResponses[keyof ProbeAcquisitionResponses];

export type GetAcquisitionData = {
    body?: never;
    path: {
        /**
         * Acquisition Id
         */
        acquisition_id: string;
    };
    query?: never;
    url: '/acquisitions/{acquisition_id}';
};

export type GetAcquisitionErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetAcquisitionResponses = {
    /**
     * Successful Response
     */
    200: AcquisitionStatus;
};

export type GetAcquisitionResponse = GetAcquisitionResponses[keyof GetAcquisitionResponses];

export type GetConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config';
};

export type GetConfigurationResponses = {
    /**
     * Successful Response
     */
    200: ConfigResponse;
};

export type GetConfigurationResponse = GetConfigurationResponses[keyof GetConfigurationResponses];

export type GetExtractionPromptsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/extraction/prompts';
};

export type GetExtractionPromptsResponses = {
    /**
     * Successful Response
     */
    200: ExtractionPromptsResponse;
};

export type GetExtractionPromptsResponse = GetExtractionPromptsResponses[keyof GetExtractionPromptsResponses];

export type ListMeetingExtractionDocumentsData = {
    body?: never;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/meetings/{meeting_id}/extraction-documents';
};

export type ListMeetingExtractionDocumentsErrors = {
    /**
     * `not-found` — no meeting with that id.
     */
    404: ProblemDetails;
    /**
     * `meeting-not-viewable` — the meeting exists but an evidence stage has not settled; the same gate every meeting-scoped read passes.
     */
    409: ProblemDetails;
    /**
     * `invalid-request` — the route parameter is not a UUID.
     */
    422: ProblemDetails;
};

export type ListMeetingExtractionDocumentsError = ListMeetingExtractionDocumentsErrors[keyof ListMeetingExtractionDocumentsErrors];

export type ListMeetingExtractionDocumentsResponses = {
    /**
     * Successful Response
     */
    200: MeetingExtractionDocumentsResponse;
};

export type ListMeetingExtractionDocumentsResponse = ListMeetingExtractionDocumentsResponses[keyof ListMeetingExtractionDocumentsResponses];

export type ListParticipantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/participants';
};

export type ListParticipantsResponses = {
    /**
     * Response Listparticipants
     *
     * Successful Response
     */
    200: Array<ParticipantRow>;
};

export type ListParticipantsResponse = ListParticipantsResponses[keyof ListParticipantsResponses];

export type RenameParticipantData = {
    body: RenameParticipantRequest;
    path: {
        /**
         * Participant Id
         */
        participant_id: string;
    };
    query?: never;
    url: '/participants/{participant_id}';
};

export type RenameParticipantErrors = {
    /**
     * `not-found` — no such participant row.
     */
    404: ProblemDetails;
    /**
     * `already-merged` — the target of a rename, the absorbed side of a merge, or an existing survivor with absorbed aliases cannot be merged again; or `merge-target-not-canonical` — the survivor side of a merge is itself already an alias key. No chained aliases (Design Notes).
     */
    409: ProblemDetails;
    /**
     * `invalid-request` — the route parameter is not a UUID, the display name is blank, or a merge names the same id twice.
     */
    422: ProblemDetails;
};

export type RenameParticipantError = RenameParticipantErrors[keyof RenameParticipantErrors];

export type RenameParticipantResponses = {
    /**
     * Successful Response
     */
    200: ParticipantRow;
};

export type RenameParticipantResponse = RenameParticipantResponses[keyof RenameParticipantResponses];

export type MergeParticipantsData = {
    body: MergeParticipantsRequest;
    path: {
        /**
         * Participant Id
         */
        participant_id: string;
    };
    query?: never;
    url: '/participants/{participant_id}/merge';
};

export type MergeParticipantsErrors = {
    /**
     * `not-found` — no such participant row.
     */
    404: ProblemDetails;
    /**
     * `already-merged` — the target of a rename, the absorbed side of a merge, or an existing survivor with absorbed aliases cannot be merged again; or `merge-target-not-canonical` — the survivor side of a merge is itself already an alias key. No chained aliases (Design Notes).
     */
    409: ProblemDetails;
    /**
     * `invalid-request` — the route parameter is not a UUID, the display name is blank, or a merge names the same id twice.
     */
    422: ProblemDetails;
};

export type MergeParticipantsError = MergeParticipantsErrors[keyof MergeParticipantsErrors];

export type MergeParticipantsResponses = {
    /**
     * Response Mergeparticipants
     *
     * Successful Response
     */
    200: Array<ParticipantRow>;
};

export type MergeParticipantsResponse = MergeParticipantsResponses[keyof MergeParticipantsResponses];

export type GetModelSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/models';
};

export type GetModelSettingsResponses = {
    /**
     * Successful Response
     */
    200: ModelSettingsResponse;
};

export type GetModelSettingsResponse = GetModelSettingsResponses[keyof GetModelSettingsResponses];

export type SelectRoleBindingData = {
    body: RoleSelectionRequest;
    path: {
        /**
         * Role
         */
        role: string;
    };
    query?: never;
    url: '/settings/roles/{role}';
};

export type SelectRoleBindingErrors = {
    /**
     * `unknown-role` — no LLM role has that name.
     */
    404: ProblemDetails;
    /**
     * `binding-not-in-catalog` — the role exists but its catalog does not offer the requested binding. `role-file-only` — the role exists but does not yet adopt persisted selection. `invalid-request` — the request body failed validation.
     */
    422: ProblemDetails;
};

export type SelectRoleBindingError = SelectRoleBindingErrors[keyof SelectRoleBindingErrors];

export type SelectRoleBindingResponses = {
    /**
     * Successful Response
     */
    200: RoleSelectionView;
};

export type SelectRoleBindingResponse = SelectRoleBindingResponses[keyof SelectRoleBindingResponses];

export type ListMeetingSpeakersData = {
    body?: never;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/meetings/{meeting_id}/speakers';
};

export type ListMeetingSpeakersErrors = {
    /**
     * `not-found` — no such meeting; it was never ingested.
     */
    404: unknown;
    /**
     * `meeting-not-viewable` — the meeting exists but its worker is running with unsettled evidence. Transient: retry once ingestion settles. A non-running unsettled job is served only by this route as the speaker-recovery read. The refusal carries the sibling reads' `meetingId`, `augmenting` (bool) and `jobStatus` (str) extensions.
     */
    409: unknown;
    /**
     * `invalid-request` — the route parameter is not a UUID.
     */
    422: ProblemDetails;
};

export type ListMeetingSpeakersError = ListMeetingSpeakersErrors[keyof ListMeetingSpeakersErrors];

export type ListMeetingSpeakersResponses = {
    /**
     * Successful Response
     */
    200: MeetingSpeakersResponse;
};

export type ListMeetingSpeakersResponse = ListMeetingSpeakersResponses[keyof ListMeetingSpeakersResponses];

export type AssignMeetingSpeakerData = {
    body: AssignSpeakerRequest;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
        /**
         * Tag
         */
        tag: string;
    };
    query?: never;
    url: '/meetings/{meeting_id}/speakers/{tag}';
};

export type AssignMeetingSpeakerErrors = {
    /**
     * `not-found` — no such meeting. `unknown-speaker-tag` — the meeting's transcript carries no segment with that label, so the assignment would never match anything. `unknown-participant` — `participantId` names no participant row.
     */
    404: unknown;
    /**
     * `assignment-target-busy` — the meeting's job is `running`, so re-arming it would race the worker; carries `jobId` and `jobStatus`. Retry once the job settles. An unviewable meeting whose job is not running is deliberately accepted by this PUT as the curator's recovery path; only the paired speakers GET receives the read half of that exception.
     */
    409: unknown;
    /**
     * `invalid-request` — the route parameter is not a UUID, or the body did not name exactly one of `participantId`, `displayName` or `unresolved: true` (a blank or NUL-bearing `displayName` is refused here too).
     */
    422: ProblemDetails;
};

export type AssignMeetingSpeakerError = AssignMeetingSpeakerErrors[keyof AssignMeetingSpeakerErrors];

export type AssignMeetingSpeakerResponses = {
    /**
     * Successful Response
     */
    200: SpeakerAssignmentResponse;
};

export type AssignMeetingSpeakerResponse = AssignMeetingSpeakerResponses[keyof AssignMeetingSpeakerResponses];

export type GetCorpusStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/corpus/stats';
};

export type GetCorpusStatsResponses = {
    /**
     * Successful Response
     */
    200: CorpusStats;
};

export type GetCorpusStatsResponse = GetCorpusStatsResponses[keyof GetCorpusStatsResponses];

export type GetSystemStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetSystemStatusResponses = {
    /**
     * Successful Response
     */
    200: StatusResponse;
};

export type GetSystemStatusResponse = GetSystemStatusResponses[keyof GetSystemStatusResponses];

export type ListSeriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/series';
};

export type ListSeriesResponses = {
    /**
     * Response Listseries
     *
     * Successful Response
     */
    200: Array<SeriesListRow>;
};

export type ListSeriesResponse = ListSeriesResponses[keyof ListSeriesResponses];

export type CreateSeriesData = {
    body: CreateNamedEntityRequest;
    path?: never;
    query?: never;
    url: '/series';
};

export type CreateSeriesErrors = {
    /**
     * `name-taken` — another row of the same entity type already carries this name (names are UNIQUE per type).
     */
    409: ProblemDetails;
    /**
     * `invalid-request` — a route parameter or body id is not a UUID, a required field is absent, or the entity name is blank, longer than 200 characters, or contains a NUL character.
     */
    422: ProblemDetails;
};

export type CreateSeriesError = CreateSeriesErrors[keyof CreateSeriesErrors];

export type CreateSeriesResponses = {
    /**
     * Successful Response
     */
    201: SeriesRow;
};

export type CreateSeriesResponse = CreateSeriesResponses[keyof CreateSeriesResponses];

export type ListProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products';
};

export type ListProductsResponses = {
    /**
     * Response Listproducts
     *
     * Successful Response
     */
    200: Array<ProductRow>;
};

export type ListProductsResponse = ListProductsResponses[keyof ListProductsResponses];

export type CreateProductData = {
    body: CreateNamedEntityRequest;
    path?: never;
    query?: never;
    url: '/products';
};

export type CreateProductErrors = {
    /**
     * `name-taken` — another row of the same entity type already carries this name (names are UNIQUE per type).
     */
    409: ProblemDetails;
    /**
     * `invalid-request` — a route parameter or body id is not a UUID, a required field is absent, or the entity name is blank, longer than 200 characters, or contains a NUL character.
     */
    422: ProblemDetails;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
    /**
     * Successful Response
     */
    201: ProductRow;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects';
};

export type ListProjectsResponses = {
    /**
     * Response Listprojects
     *
     * Successful Response
     */
    200: Array<ProjectListRow>;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: CreateProjectRequest;
    path?: never;
    query?: never;
    url: '/projects';
};

export type CreateProjectErrors = {
    /**
     * `not-found` — no such meeting, series, project, or product row.
     */
    404: ProblemDetails;
    /**
     * `name-taken` — another row of the same entity type already carries this name (names are UNIQUE per type).
     */
    409: ProblemDetails;
    /**
     * `invalid-request` — a route parameter or body id is not a UUID, a required field is absent, or the entity name is blank, longer than 200 characters, or contains a NUL character.
     */
    422: ProblemDetails;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    201: ProjectRow;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type AssignProjectProductData = {
    body: AssignProjectProductRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type AssignProjectProductErrors = {
    /**
     * `not-found` — no such meeting, series, project, or product row.
     */
    404: ProblemDetails;
    /**
     * `invalid-request` — a route parameter or body id is not a UUID, a required field is absent, or the entity name is blank, longer than 200 characters, or contains a NUL character.
     */
    422: ProblemDetails;
};

export type AssignProjectProductError = AssignProjectProductErrors[keyof AssignProjectProductErrors];

export type AssignProjectProductResponses = {
    /**
     * Successful Response
     */
    200: ProjectRow;
};

export type AssignProjectProductResponse = AssignProjectProductResponses[keyof AssignProjectProductResponses];

export type AssignMeetingSeriesData = {
    body: AssignMeetingSeriesRequest;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/meetings/{meeting_id}/series';
};

export type AssignMeetingSeriesErrors = {
    /**
     * `not-found` — no such meeting, series, project, or product row.
     */
    404: ProblemDetails;
    /**
     * `invalid-request` — a route parameter or body id is not a UUID, a required field is absent, or the entity name is blank, longer than 200 characters, or contains a NUL character.
     */
    422: ProblemDetails;
};

export type AssignMeetingSeriesError = AssignMeetingSeriesErrors[keyof AssignMeetingSeriesErrors];

export type AssignMeetingSeriesResponses = {
    /**
     * Successful Response
     */
    200: MeetingSeriesAssignment;
};

export type AssignMeetingSeriesResponse = AssignMeetingSeriesResponses[keyof AssignMeetingSeriesResponses];

export type AssignMeetingProjectData = {
    body: AssignMeetingProjectRequest;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/meetings/{meeting_id}/project';
};

export type AssignMeetingProjectErrors = {
    /**
     * `not-found` — no such meeting, series, project, or product row.
     */
    404: ProblemDetails;
    /**
     * `invalid-request` — a route parameter or body id is not a UUID, a required field is absent, or the entity name is blank, longer than 200 characters, or contains a NUL character.
     */
    422: ProblemDetails;
};

export type AssignMeetingProjectError = AssignMeetingProjectErrors[keyof AssignMeetingProjectErrors];

export type AssignMeetingProjectResponses = {
    /**
     * Successful Response
     */
    200: MeetingProjectAssignment;
};

export type AssignMeetingProjectResponse = AssignMeetingProjectResponses[keyof AssignMeetingProjectResponses];

export type ListThreadsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/threads';
};

export type ListThreadsResponses = {
    /**
     * Successful Response
     */
    200: ThreadsResponse;
};

export type ListThreadsResponse = ListThreadsResponses[keyof ListThreadsResponses];

export type ListThreadSuggestionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Minmeetings
         */
        minMeetings?: number;
        /**
         * Maxmeetings
         */
        maxMeetings?: number;
        /**
         * Minspandays
         */
        minSpanDays?: number;
    };
    url: '/threads/suggestions';
};

export type ListThreadSuggestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListThreadSuggestionsError = ListThreadSuggestionsErrors[keyof ListThreadSuggestionsErrors];

export type ListThreadSuggestionsResponses = {
    /**
     * Successful Response
     */
    200: SuggestionsResponse;
};

export type ListThreadSuggestionsResponse = ListThreadSuggestionsResponses[keyof ListThreadSuggestionsResponses];

export type TraceThreadData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Threadid
         */
        threadId?: string | null;
        /**
         * Permeeting
         */
        perMeeting?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/threads/trace';
};

export type TraceThreadErrors = {
    /**
     * `invalid-request` — neither `q` nor `threadId` was given.
     */
    400: unknown;
    /**
     * `not-found` — no thread with that id.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * `thread-trace-store-unavailable`, `thread-trace-store-unusable` or `embedder-unusable` — the sample leg could not be served, and is refused rather than degraded to silence.
     */
    503: unknown;
};

export type TraceThreadError = TraceThreadErrors[keyof TraceThreadErrors];

export type TraceThreadResponses = {
    /**
     * Successful Response
     */
    200: ThreadTrace;
};

export type TraceThreadResponse = TraceThreadResponses[keyof TraceThreadResponses];

export type GetThreadTimelineData = {
    body?: never;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: {
        /**
         * Level
         */
        level?: 'bands' | 'meetings' | 'moments' | 'evidence';
        /**
         * From
         */
        from?: string | null;
        /**
         * To
         */
        to?: string | null;
    };
    url: '/threads/{thread_id}/timeline';
};

export type GetThreadTimelineErrors = {
    /**
     * `invalid-window` — `from` is after `to`.
     */
    400: unknown;
    /**
     * `not-found` — no thread with that id.
     */
    404: unknown;
    /**
     * `invalid-request` — the id is not a UUID, or `level` is not one of `bands|meetings|moments|evidence`.
     */
    422: ProblemDetails;
};

export type GetThreadTimelineError = GetThreadTimelineErrors[keyof GetThreadTimelineErrors];

export type GetThreadTimelineResponses = {
    /**
     * Response Getthreadtimeline
     *
     * Successful Response
     */
    200: ({
        level: 'bands';
    } & BandsTimeline) | ({
        level: 'meetings';
    } & MeetingsTimeline) | ({
        level: 'moments';
    } & MomentsTimeline) | ({
        level: 'evidence';
    } & EvidenceTimeline);
};

export type GetThreadTimelineResponse = GetThreadTimelineResponses[keyof GetThreadTimelineResponses];

export type CreateUploadSessionData = {
    /**
     * UploadSessionRequest
     */
    body: {
        /**
         * The meeting's human label, shown in the app.
         */
        title: string;
        /**
         * When the meeting started: RFC 3339 with an offset (2026-08-05T12:00:19Z). A date alone is refused — an upload never records day precision.
         */
        startedAt: string;
        /**
         * Always 'real'. Scripted meetings are eval subjects and are minted on the api host.
         */
        corpus: 'real';
        /**
         * Which export the transcript is. Required whenever a .vtt is attached; declared, never detected.
         */
        transcriptDialect?: 'plain' | 'teams-vtt' | 'zoom';
        /**
         * Who supplied the files, recorded in provenance.
         */
        suppliedBy?: string;
        /**
         * The recording and/or transcript. The role is decided by the file extension: .mp4 becomes recording.mp4, .vtt transcript.vtt, .txt transcript.txt.
         */
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/uploads';
};

export type CreateUploadSessionErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Request Entity Too Large
     */
    413: unknown;
    /**
     * Unsupported Media Type
     */
    415: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
    /**
     * Service Unavailable
     */
    503: unknown;
};

export type CreateUploadSessionResponses = {
    /**
     * Successful Response
     */
    201: UploadSessionView;
};

export type CreateUploadSessionResponse = CreateUploadSessionResponses[keyof CreateUploadSessionResponses];

export type DeleteUploadSessionData = {
    body?: never;
    path: {
        /**
         * Upload Session Id
         */
        upload_session_id: string;
    };
    query?: never;
    url: '/uploads/{upload_session_id}';
};

export type DeleteUploadSessionErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
    /**
     * Service Unavailable
     */
    503: unknown;
};

export type DeleteUploadSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUploadSessionResponse = DeleteUploadSessionResponses[keyof DeleteUploadSessionResponses];

export type GetUploadSessionData = {
    body?: never;
    path: {
        /**
         * Upload Session Id
         */
        upload_session_id: string;
    };
    query?: never;
    url: '/uploads/{upload_session_id}';
};

export type GetUploadSessionErrors = {
    /**
     * Not Found
     */
    404: unknown;
    /**
     * Unprocessable Entity
     */
    422: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
    /**
     * Service Unavailable
     */
    503: unknown;
};

export type GetUploadSessionResponses = {
    /**
     * Successful Response
     */
    200: UploadSessionView;
};

export type GetUploadSessionResponse = GetUploadSessionResponses[keyof GetUploadSessionResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
